config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'home#index'

  match '/need_help',   to: 'home#need_help',   via: 'get'
  match '/about',       to: 'home#about',       via: 'get'
  match '/contact',     to: 'home#contact',     via: 'get'
  match '/status',      to: 'home#status',      via: 'get'
  match '/watch_list',  to: 'home#watch_list',  via: 'get'
  match '/new_display', to: 'home#new_display', via: 'get'
  match '/detailed',    to: 'home#detailed',    via: 'get'
  match '/search',      to: 'home#search',      via: 'get'

  devise_for :users, controllers: { registrations: 'user/registrations' }

  resources :users do
    member do
      get 'talks'
      get 'negotiations'
      get 'offerings'
      get 'wants'
      get 'payments'
      get 'entries'
      get 'contracts'
      get 'entrusts'
      get 'recent_contracts'
      get 'recent_entrusts'
      get :following, :followers
    end
  end
  match '/users/profile/edit', to: 'users#edit', via: 'get'

  resources :offerings
  resources :wants
  resources :entries
  resources :contracts
  resources :entrusts
  resources :messages
  resources :talks
  resources :negotiations
  resource :account
  resources :payments
  resources :entries, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/models/want.rb
class Want < Task
end

app/controllers/wants_controller.rb
class WantsController < ApplicationController
  before_action :set_want, only: [:show, :update, :destroy]
  before_action :authenticate_user!

  def index
    @categories = Category.all
    @class_name = Want
  end

  def show
    @class_name = Want
    @task = @want
    @entry = Entry.new(price: 1)
  end

  def new
    @class_name = Want
    @task = Want.new
    @categories = Category.all
  end

  def edit
    @class_name = Want
    @want = Want.find(params[:id])
    @task = @want
    @categories = Category.all
    if @want.user != current_user
      redirect_to @want, alert: t('You cannot edit!')
    end
  end

  def create
    @want = Want.new(want_params)
    @want.user = current_user
    @categories = Category.all

    respond_to do |format|
      if @want.save
        format.html { redirect_to @want, notice: t('activerecord.successful.messages.created', model: Want.model_name.human) }
        format.json { render action: 'show', status: :created, location: @want }
      else
        format.html { render action: 'new' }
        format.json { render json: @want.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
          if @want.user == current_user && @want.update(want_params)
        format.html { redirect_to @want, notice: t('activerecord.successful.messages.updated', model: Want.model_name.human) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @want.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @want.user == current_user
      @want.destroy
      respond_to do |format|
        format.html { redirect_to wants_user_url(current_user) }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to wants_user_url(current_user), alert: t('You cannot delete!') }
        format.json { head :no_content }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_want
    @want = Want.find(params[:id])
    @categories = Category.all
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def want_params
    params.require(:want).permit(:title, :category_id, :description, :price_description, :opened)
  end
end

app/views/wants/_entry.html.erb
<div class="ui-body ui-body-a ui-corner-all">
  <%= form_for(@entry) do |f| %>
    <%= f.hidden_field :task_id, value: @task.id %>
    <div class="field ui-field-contain">
      <%= f.label :expected_at %>
      <%= f.datetime_select :expected_at, {}, data: { role: "none"} %>
    </div>
    <div class="field ui-field-contain">
      <%= f.label :price %>
      <%= f.number_field :price, min: 1 %>
    </div>
    <%= f.submit t('Contract') %>
  <% end %>
</div>

app/views/wants/edit.html.erb
<% provide :title, t('Editing ', model: @class_name.model_name.human) %>
<h1><%= yield(:title) %></h1>

<%= render 'tasks/form' %>

<%= link_to t('Back'), @task, class: "ui-btn ui-icon-arrow-l ui-btn-icon-left" %>

app/views/wants/index.html.erb
<% provide :locale, I18n.locale.inspect %>
<% provide :title,  t("Listing ", model: Want.model_name.human.pluralize(:locale)) %>
<h1><%= yield(:title) %></h1>

<% if @categories.present? %>
  <div data-role="collapsibleset">
    <% @categories.each do |category| %>
      <% wants = category.wants.readable.where.not(user_id: current_user.id) %>
      <% if wants.present? %>
        <div data-role="collapsible" data-theme="b" data-content-theme="a">
          <h2><%= category.name %>: <span><%= wants.count %></span></h2>
          <% if wants.count > 10 %>
            <ul data-role="listview" data-filter="true" data-filter-placeholder="検索キーワード">
          <% else %>
            <ul data-role="listview">
          <% end %>
            <% wants.each do |want| %>
              <li><%= link_to want.title, want %></li>
            <% end %>
          </ul>
       </div>
      <% end %>
    <% end %>
  </div>
<% else %>
  <p><%= t("There is no ", model: Category.model_name.human) %></p>
<% end %>

app/views/wants/new.html.erb
<% provide :title, t('New ', model: @class_name.model_name.human) %>
<h1><%= yield(:title) %></h1>

<%= render 'tasks/form' %>

<%= link_to t('Back'), wants_user_path(current_user), class: "ui-btn ui-icon-arrow-l ui-btn-icon-left" %>

app/views/wants/show.html.erb
<% provide :title, @class_name.model_name.human %>
<h1><%= yield(:title) %></h1>

<% if current_user?(@task.user) %>
  <div class="ui-body ui-body-a ui-corner-all">
<% end %>

<%= render 'tasks/task' %>

<% if current_user?(@task.user) %>
    <%= link_to t('Edit'), edit_want_path(@task), class: "ui-btn ui-btn-inline" %>
    <%= link_to t('Destroy'), @task, method: :delete, data: { confirm: t('Are you sure?') }, class: "ui-btn ui-btn-inline" %>
  </div>
  <%= link_to t('Back to my wants'), wants_user_path(current_user), data: { role: :button, icon: "arrow-l" } %>
<% end %>

<%= render 'wants/entry' if !current_user?(@task.user) %>

<% if !current_user?(@task.user) %>
  <%= link_to t('Back'), wants_path, class: "ui-btn ui-icon-arrow-l ui-btn-icon-left"  %>
<% end %>