config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'home#index'

  match '/need_help',   to: 'home#need_help',   via: 'get'
  match '/about',       to: 'home#about',       via: 'get'
  match '/contact',     to: 'home#contact',     via: 'get'
  match '/status',      to: 'home#status',      via: 'get'
  match '/watch_list',  to: 'home#watch_list',  via: 'get'
  match '/new_display', to: 'home#new_display', via: 'get'
  match '/detailed',    to: 'home#detailed',    via: 'get'
  match '/search',      to: 'home#search',      via: 'get'

  devise_for :users, controllers: { registrations: 'user/registrations' }

  resources :users do
    member do
      get 'talks'
      get 'negotiations'
      get 'offerings'
      get 'wants'
      get 'payments'
      get 'entries'
      get 'contracts'
      get 'entrusts'
      get 'recent_contracts'
      get 'recent_entrusts'
      get :following, :followers
    end
  end
  match '/users/profile/edit', to: 'users#edit', via: 'get'

  resources :offerings
  resources :wants
  resources :entries
  resources :contracts
  resources :entrusts
  resources :messages
  resources :talks
  resources :negotiations
  resource :account
  resources :payments
  resources :entries, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  after_create :creating_account

  has_one :account,    dependent: :destroy
  def account_id
    account.id
  end

  has_many :tasks,     dependent: :destroy
  has_many :offerings, dependent: :destroy
  has_many :wants,     dependent: :destroy
  has_many :entries, foreign_key: 'owner_id'
  has_many :reverse_entries, foreign_key: 'contractor_id', class_name: 'Entry'

  has_many :sended_messages,   class_name: 'Message', foreign_key: 'sender_id'
  has_many :received_messages, class_name: 'Message', foreign_key: 'recepient_id'
  has_many :senders,    through: :received_messages, source: :sender
  has_many :recepients, through: :sended_messages,   source: :recepient

  has_many :relationships,         foreign_key: 'follower_id', dependent: :destroy
  has_many :reverse_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :followed_users, through: :relationships,         source: :followed
  has_many :followers,      through: :reverse_relationships, source: :follower # source:は省略可

  has_many :notifications, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable

  validates :name, presence: true
  validates :admin, inclusion: { in: [true, false] }

  scope :active, -> { where.not(confirmed_at: nil).where(deleted_at: nil) }

  #
  # Talk関係メソッド
  #
  def talks(companion = nil)
    if companion.present?
      messages = Talk.between(self, companion)
      #messages = Talk.where('sender_id = :id and recepient_id = :companion_id or sender_id = :companion_id and recepient_id = :id', id: id, companion_id: companion.id)
    else
      messages = Talk.with(self)
      #messages = Talk.where('sender_id = :id or recepient_id = :id', id: id)
    end
    messages
  end

  def companions
    sql =  'SELECT DISTINCT * FROM ('
    sql += 'SELECT users.*, messages.created_at AS messages_created_at FROM users'
    sql += " INNER JOIN messages ON users.id = messages.sender_id WHERE messages.type = 'Talk' AND messages.recepient_id = :id"
    sql += ' UNION '
    sql += 'SELECT users.*, messages.created_at AS messages_created_at FROM users'
    sql += " INNER JOIN messages ON users.id = messages.recepient_id WHERE messages.type = 'Talk' AND messages.sender_id = :id"
    sql += ') AS companions ORDER BY messages_created_at DESC'
    companions = User.find_by_sql([sql, { id: id }])
    companions
  end

  #
  # Account関係メソッド
  #
  def pay_to!(recepient, args = {})
    Account.transfer(
      sender_account: self.account,
      recepient_account: recepient.account,
      amount: args[:amount],
      subject: args[:subject],
      comment: args[:commnet]
    )
    # notificationはAccountで実行
  end

  #
  # Relationship関係メソッド
  #
  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
    # TODO: notificationはRelationshipで実行
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
    # TODO: notificationはRelationshipで実行
  end

  #
  # Entry関係メソッド
  #
  def entry!(entry)
    entry.save!
    entry = commit!(entry, had_nofied: true)
    notify_entry!(entry)
    entry
  end

  def commit!(entry, args = {})
    # 状態のチェック
    unless entry.commitable?(self)
      fail "Couldn't find Entry with 'id'=#{entry.id} and it's status be able to commit by #{id}'}"
    end

    # 引数の設定
    expected_at  = (args.key?(:expected_at) && args[:expected_at].present?) ? args[:expected_at] : entry.expected_at
    price        = (args.key?(:price) && args[:price].present?) ? args[:price] : entry.price

    if entry.owner?(self)
      entry = owner_commit!(entry, expected_at: expected_at, price: price)
    elsif entry.contractor?(self)
      entry = contractor_commit!(entry, expected_at: expected_at, price: price)
    else
      fail "Couldn't find Entry with 'id'=#{target_entry.id} and 'user_id'=#{id} or 'task.user_id'=#{id}"
    end

    notify_commit!(entry) unless args.key?(:had_nofied) && args[:had_nofied].present?
    entry
  end

  def cancel!(entry)
    # 状態のチェック
    unless entry.cancelable?(self)
      fail "Couldn't find Entry with 'id'=#{entry.id} and it's status be able to cancel'}"
    end

    if entry.owner == self
      entry.update!(owner_canceled_at: Time.now)
    elsif entry.contractor == self
      entry.update!(contractor_canceled_at: Time.now)
    else
      fail "Couldn't find Entry with 'id'=#{target_entry.id} and 'user_id'=#{id} or 'task.user_id'=#{id}"
    end

    notify_cancel!(entry.reload)
    entry
  end

  def perform!(entry)
    unless entry.performable?(self)
      fail "Couldn't find Entry with 'id'=#{entry.id} and it's status be able to perform'}"
    end

    unless entry.performer?(self)
      fail "Couldn't find Entry with 'id'=#{target_entry.id} and user 'id'=#{id} can be able to perform"
    end

    entry.update!(performed_at: Time.now)
    notify_perform!(entry.reload)
    entry
  end

  def pay_for!(entry, args = {})
    unless entry.payable?(self)
      fail "Couldn't find Entry with 'id'=#{entry.id} and it's status be able to pay'}"
    end

    unless entry.payer?(self)
      fail "Couldn't find Entry with 'id'=#{entry.id} and user 'id'=#{id} can be able to pay"
    end

    recepient = entry.payee
    amount  = (args.key?(:amount) && args[:amount].present?) ? args[:amount] : entry.price
    subject = "#{entry.title}の支払"
    comment = args[:comment]

    payment = pay_to!(recepient, amount: amount, subject: subject, comment: comment)
    entry.update!(paid_at: Time.now, payment: payment)

    notify_pay_for!(entry.reload)
    entry
  end

  # instead of deleting, indicate the user requested a delete & timestamp it
  def soft_delete
    update_attribute(:deleted_at, Time.current)
  end

  # ensure user account is active
  def active_for_authentication?
    super && !deleted_at
  end

  # provide a custom message for a deleted account
  def inactive_message
    !deleted_at ? super : :deleted_account
  end

  private

  def owner_commit!(entry, args = {})
    recent_price = entry.price
    recent_expected_at = entry.expected_at
    entry.update!(
        owner_committed_at: Time.now,
        expected_at: args[:expected_at],
        price: args[:price]
    )
    entry.reload
    if entry.expected_at != recent_expected_at || entry.price != recent_price
      entry.update!(contractor_committed_at: nil)      
    end
    entry
  end

  def contractor_commit!(entry, args = {})
    recent_price = entry.price
    recent_expected_at = entry.expected_at
    entry.update!(
        contractor_committed_at: Time.now,
        expected_at: args[:expected_at],
        price: args[:price]
    )
    entry.reload
    if entry.expected_at != recent_expected_at || entry.price != recent_price
      entry.update!(owner_committed_at: nil)      
    end
    entry
  end

  def notify_entry!(entry)
    recepient = entry.partner_of(self)

    if entry.contractor?(self)
      body = "#{name}さんが「#{entry.title}」を引き受けました。条件を調整してください。"
    elsif entry.owner?(self)
      body = "#{name}さんが「#{entry.title}」を依頼しました。条件を調整してください。"
    end

    Notification.create!(
      user: recepient,
      body: body,
      url: entry.url
    )
  end

  def notify_commit!(entry)
    recepient = entry.partner_of(self)

    if entry.commitable?(self)
      body = "#{name}さんが「#{entry.title}」の条件を変更しました。条件を調整してください。"
    else
      body = "#{name}さんと「#{entry.title}」の契約が成立しました。"
    end

    notification = recepient.notifications.find_by(url: entry.url)
    if notification.present?
      notification.update!(user: recepient, body: body, url: entry.url, read_at: nil)
    else
      Notification.create!(user: recepient, body: body, url: entry.url)
    end
  end

  def notify_cancel!(entry)
    recepient = entry.partner_of(self)
    body = "#{name}さんが「#{entry.title}」をキャンセルしました。"

    notification = recepient.notifications.find_by(url: entry.url)
    if notification.present?
      notification.update!(user: recepient, body: body, url: entry.url, read_at: nil)
    else
      Notification.create!(user: recepient, body: body, url: entry.url)
    end
  end

  def notify_perform!(entry)
    recepient = entry.partner_of(self)
    body = "#{name}さんが「#{entry.title}」を実施しました。"
    notification = recepient.notifications.find_by(url: entry.url)
    notification.update!(user: recepient, body: body, url: entry.url, read_at: nil)
  end

  def notify_pay_for!(entry)
    recepient = entry.partner_of(self)
    body = "#{name}さんが「#{entry.title}」に支払いました。"
    notification = recepient.notifications.find_by(url: entry.url)
    notification.update!(user: recepient, body: body, url: entry.url, read_at: nil)
  end

  def creating_account
    self.create_account(balance: 1000)
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  # POST /resource
  def create
    build_resource(sign_up_params)

    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  # DELETE /resource  
  def destroy  
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)  
    set_flash_message :notice, :destroyed if is_flashing_format?  
    yield resource if block_given?  
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }  
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :update]

  def index
    @users = User.where.not(id: current_user.id).active
  end

  def show
  end

  def edit
    @user = current_user
  end

  def update
    respond_to do |format|
      if @user == current_user && @user.update(user_params)
          format.html { redirect_to root_path, notice: t('activerecord.successful.messages.updated', model: User.model_name.human) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def talks
    @user = User.find(params[:id])
    @talks = current_user.talks(@user).order('created_at DESC').paginate(page: params[:page])
    @talk = Talk.new
    @talk.recepient_id = @user.id
    @talk.sender_id = current_user.id
  end

  def offerings
    @class_name = Offering
    @user = User.find(params[:id])
    @tasks = @user.offerings
    render 'tasks'
  end

  def wants
    @class_name = Want
    @user = User.find(params[:id])
    @tasks = @user.wants
    render 'tasks'
  end

  def contracts
    @class_name = 'Contract'
    @user = User.find(params[:id])
    @entries = Entry.in_progress.where(contractor_id: @user.id).order('updated_at DESC')
    render 'contracts'
  end

  def entrusts
    @class_name = 'Entrust'
    @user = User.find(params[:id])
    @entries = Entry.in_progress.where(owner_id: @user.id).order('updated_at DESC')
    render 'entrusts'
  end

  def recent_contracts
    @class_name = 'Contract'
    @user = User.find(params[:id])
    not_finished = Entry.not_finished
    not_finished = not_finished.where_values.reduce(:and)
    not_owner_canceled = Entry.not_owner_canceled
    not_owner_canceled = not_owner_canceled.where_values.reduce(:and)
    not_contractor_canceled = Entry.not_contractor_canceled
    not_contractor_canceled = not_contractor_canceled.where_values.reduce(:and)
    @entries = Entry.where(not_finished.or(not_owner_canceled).or(not_contractor_canceled)).where(contractor_id: @user.id).order('updated_at DESC')
    render 'contracts'
  end

  def recent_entrusts
    @class_name = 'Entrust'
    @user = User.find(params[:id])
    not_finished = Entry.not_finished
    not_finished = not_finished.where_values.reduce(:and)
    not_owner_canceled = Entry.not_owner_canceled
    not_owner_canceled = not_owner_canceled.where_values.reduce(:and)
    not_contractor_canceled = Entry.not_contractor_canceled
    not_contractor_canceled = not_contractor_canceled.where_values.reduce(:and)
    @entries = Entry.where(not_finished.or(not_owner_canceled).or(not_contractor_canceled)).where(owner_id: @user.id).order('updated_at DESC')
    render 'entrusts'
  end

  def following
    @title = 'follows'
    @no_user = 'No followed user'
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = 'is followed by'
    @no_user = 'No follower'
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  def entries
    @user = User.find(params[:id])
    @contracts = []
    @entrusts = []
    entries = @user.entries
    entries.each do |entry|
      if entry.task.type == 'Offering'
        @contracts.push(entry)
      elsif entry.task.type == 'Want'
        @entrusts.push(entry)
      end
    end
    render 'entries'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :description, :email)
  end
end

app/views/users/_balance.html.erb
<!-- <div class="ui-body ui-body-a ui-corner-all"> -->
<p><strong><%= t('Current balance') %></strong>: <%= @user.account.balance %><%= t('points') %></p>
<!-- </div> -->

app/views/users/_description.html.erb
<!-- <div class="ui-body ui-body-a ui-corner-all"> -->
  <p><strong><%= User.human_attribute_name(:description) %></strong><br><%= simple_format @user.description %></p>
<!-- </div> -->

app/views/users/_edit_settings.html.erb
<ul data-role="listview" data-inset="true">
  <li><%= link_to t("Personal settings"), users_profile_edit_path %></li>
  <li><%= link_to t("Account settings"), edit_user_registration_path %></li>
</ul>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_notifications_and_talks.html.erb
<div class="ui-body ui-body-a ui-corner-all">
  <ul data-role="listview" data-inset="true">
    </li>
    <li>
      <%= link_to notifications_path do %>
        <%= Notification.model_name.human %>
        <span class="ui-li-count"><%= @notifications_count %></span>
      <% end %>
    </li>
  </ul>
  <ul data-role="listview" data-inset="true">
    <li><%= link_to Talk.model_name.human, talks_path %></li>
  </ul>
  </ul>
</div>

app/views/users/_recent_trades.html.erb
<div class="ui-body ui-body-a ui-corner-all">
  <h2>以前のもの</h2>
  <ul data-role="listview" data-inset="true">
    <li><%= link_to t('activerecord.models.contract'), recent_contracts_user_path(current_user) %></li>
    <li><%= link_to t('activerecord.models.entrust'), recent_entrusts_user_path(current_user) %></li>
  </ul>
  <ul data-role="listview" data-inset="true">
  </ul>
</div>

app/views/users/_services_on_display.html.erb
<div class="ui-body ui-body-a ui-corner-all">
  <h2>公開しているもの</h2>
  <ul data-role="listview" data-inset="true">
    <li><%= link_to Offering.model_name.human, offerings_user_path(current_user) %></li>
    <li><%= link_to Want.model_name.human, wants_user_path(current_user) %></li>
  </ul>
</div>

app/views/users/_trades_in_progress.html.erb
<div class="ui-body ui-body-a ui-corner-all">
  <h2>進行中のもの</h2>
  <ul data-role="listview" data-inset="true">
    <li><%= link_to t('activerecord.models.contract'), contracts_user_path(current_user) %></li>
    <li><%= link_to t('activerecord.models.entrust'), entrusts_user_path(current_user) %></li>
  </ul>
  <ul data-role="listview" data-inset="true">
  </ul>
</div>

app/views/users/_user.html.erb
<li>
  <a href="<%= user_path(user) %>">
    <%= gravatar_for user, size: 16, class: "ui-li-icon" %>
  	<%= user.name %>
  </a>
</li>

app/views/users/contracts.html.erb
<% provide :locale, I18n.locale.inspect %>
<% provide :title,  t("Listing ", model: t("activerecord.models.#{@class_name.downcase}").pluralize(:locale)) %>
<h1><%= yield(:title) %></h1>

<% if @entries.any? %>
  <table class="ui-body-a">
    <tr>
      <th><%= Entry.human_attribute_name(:expected_at) %></th>
      <th><%= Entry.human_attribute_name(:title) %></th>
      <th><%= Entry.human_attribute_name(:owner) %></th>
      <th><%= Entry.human_attribute_name(:status) %></th>
    </tr>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= l(entry.expected_at) if entry.expected_at %></td>
        <td><%= link_to entry.title, entry %></td>
        <td>
          <%= gravatar_for entry.owner, size: 16 %>
          <%= link_to entry.owner.name, entry %>
        </td>
        <td><%= t(entry.status) %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p><%= t("There is no ", model: t("activerecord.models.#{@class_name.downcase}")) %></p>
<% end %>

app/views/users/entries.html.erb
<% provide :locale, I18n.locale.inspect %>
<% provide :title,  t("Listing ", model: t("activerecord.models.#{@class_name.downcase}").pluralize(:locale)) %>
<h1><%= yield(:title) %></h1>

<% if @entries.any? %>
  <table class="ui-body-a">
    <tr>
      <th><%= Entry.human_attribute_name(:expected_at) %></th>
      <th><%= Entry.human_attribute_name(:title) %></th>
      <th><%= Entry.human_attribute_name(:owner) %></th>
      <th><%= Entry.human_attribute_name(:status) %></th>
    </tr>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= l(entry.expected_at) if entry.expected_at %></td>
        <td><%= link_to entry.title, entry %></td>
        <td>
          <%= gravatar_for entry.owner, size: 16 %>
          <%= link_to entry.owner.name, entry %>
        </td>
        <td><%= t(entry.status) %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p><%= t("There is no ", model: t("activerecord.models.#{@class_name.downcase}")) %></p>
<% end %>

app/views/users/index.html.erb
<% provide :title, t("Listing ", model: User.model_name.human.pluralize(:locale)) %>
<h1><%= yield(:title) %></h1>

<% if @users.count > 10 %>
  <ul data-role="listview" data-inset="true" data-divider-theme="d" data-filter="true" data-filter-theme="c" data-filter-placeholder="検索キーワード">
<% else %>
  <ul data-role="listview" data-inset="true" data-divider-theme="d">
<% end %>
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</ul>

app/views/users/show_follow.html.erb
<% provide(:title, t(@title)) %>
<h1><%= @user.name %><%= t(@title) %></h1>
<% if @users.any? %>
  <ul data-role="listview" data-inset="true">
    <%= render @users %>
  </ul>
<% else %>
  <%= t(@no_user) %>
<% end %>

app/views/users/talks.html.erb
<% provide :title, t("talk with", companion: @user.name) %>
<h1><%= yield(:title) %></h1>

<div class="ui-body ui-body-a ui-corner-all">
  <%= form_for(@talk) do |f| %>
    <%= f.hidden_field :sender_id %>
    <%= f.hidden_field :recepient_id %>
    <%= f.text_area :body %>
    <%= f.submit t("Submit new talk") %>
  <% end %>
</div>
<hr>

<% if @talks.present? %>
  <%= will_paginate @talks,
      renderer: WillPaginate::ActionView::JqueryMobilePaginateLinkRenderer,
      previous_label: t('Prev'),
      next_label: t('Next')
  %>
  <% @talks.each do |talk| %>
  <% talk.sender_id == current_user.id ? float = "right" : float = "left" %>
  <div class="ui-body ui-body-a ui-corner-all talk-<%= float %>">
    <p><%= gravatar_for talk.sender, size: 16 %>&nbsp;<%= talk.sender.name %></p>
    <p><%= simple_format talk.body %></p>
    <p><%= l(talk.created_at) %></p>
  </div>
  <% end %>
  <br style="clear: both;">
  <%= will_paginate @talks,
      renderer: WillPaginate::ActionView::JqueryMobilePaginateLinkRenderer,
      previous_label: t('Prev'),
      next_label: t('Next')
  %>
<% else %>
  <p><%= t("There is no ", model: Talk.model_name.human) %></p>
<% end %>