config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'home#index'

  match '/need_help',   to: 'home#need_help',   via: 'get'
  match '/about',       to: 'home#about',       via: 'get'
  match '/contact',     to: 'home#contact',     via: 'get'
  match '/status',      to: 'home#status',      via: 'get'
  match '/watch_list',  to: 'home#watch_list',  via: 'get'
  match '/new_display', to: 'home#new_display', via: 'get'
  match '/detailed',    to: 'home#detailed',    via: 'get'
  match '/search',      to: 'home#search',      via: 'get'

  devise_for :users, controllers: { registrations: 'user/registrations' }

  resources :users do
    member do
      get 'talks'
      get 'negotiations'
      get 'offerings'
      get 'wants'
      get 'payments'
      get 'entries'
      get 'contracts'
      get 'entrusts'
      get 'recent_contracts'
      get 'recent_entrusts'
      get :following, :followers
    end
  end
  match '/users/profile/edit', to: 'users#edit', via: 'get'

  resources :offerings
  resources :wants
  resources :entries
  resources :contracts
  resources :entrusts
  resources :messages
  resources :talks
  resources :negotiations
  resource :account
  resources :payments
  resources :entries, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:status]

  def index
  end

  def need_help
  end

  def about
  end

  def contact
  end

  def status
  end

  def watch_list
  end

  def new_display
  end

  def search
  end

  def detailed
  end
end

app/views/home/_index_not_signed_in.html.erb
<% provide :title, t("Koubata Project") %>

<%= render 'home/welcome' %>
<br>
<%= render 'home/sign_in_links' %>

app/views/home/_index_signed_in.html.erb
<% provide :title, t("My Status") %>
<% @user ||= current_user %>

<div class="ui-body ui-body-a ui-corner-all">
  <h1><%= t(yield(:title)) %></h1>
  <%= render 'users/profile' %>
  <br>
  <%= render 'users/notifications_and_talks' %>
  <br>
  <%= render 'users/trades_in_progress' %>
  <br>
  <%= render 'users/services_on_display' %>
  <br>
  <%= render 'users/recent_trades' %>
</div>

app/views/home/_info.html.erb
<div class="ui-body ui-body-a ui-corner-all">
  <ul data-role="listview" data-inset="true">
    <li><%= link_to t("About"), about_path %></li>
    <li><%= link_to t("Contact"), contact_path %></li>
  </ul>
</div>

app/views/home/_sign_in_links.html.erb
<div class="ui-body ui-body-a ui-corner-all">
  <%= link_to t("Sign in"), new_user_session_path, data: { ajax: false }, class: "ui-btn ui-icon-arrow-r ui-btn-icon-right" %>
  <%= link_to t("Forgot your password?"), new_password_path(resource_name), data: { ajax: false }, class: "ui-btn ui-icon-arrow-r ui-btn-icon-right" %>
</div>

app/views/home/_welcome.html.erb
<div class="ui-body ui-body-a ui-corner-all">
  <p><%= t('Welcome to Koubata Project!') %></p>
  <p><%= t('Be happy by using eco money!') %></p>
  <p><%= t("If you don't have an account you can sign up!") %></p>
  <%= link_to t("Sign up"), new_user_registration_path, class: "ui-btn ui-icon-arrow-r ui-btn-icon-right" %>
</div>

app/views/home/about.html.erb
<% provide :title, t("About") %>
<h1><%= yield(:title) %></h1>
<p>「ハッピー幸畑たすけあい」は、わたしたち一人一人ができることを共有して、みんなで楽しい街をつくる試みです。</p>
<p>あなたの「できること」「頼みたいこと」を教えてください。</p>
<p>そして、お互いにできることをして、みんなでしあわせな街をつくりましょう。</p>
<%= link_to t('Detailed'), detailed_path, class: 'ui-btn' %>

app/views/home/contact.html.erb
<% provide :title, t("Contact") %>
<h1><%= yield(:title) %></h1>
<p>青森大学地域貢献センター</p>
<p>センター長: 柏谷 至(かしわや・いたる)</p>
<p>電話: 017-738-2001</p>

app/views/home/detailed.html.erb
<% provide :title, t("Detailed") %>
<h1><%= yield(:title) %></h1>
<ol>
<li>登録すると「幸」というポイントがもらえます。</li>
<li>自分の「できること」「頼みたいこと」を登録します。</li>
<li>互いの「できること」「頼みたいこと」を見ます。</li>
<li>誰かの「頼みたいこと」を自分ができる場合、「できること」を自分が頼みたい場合、連絡して交渉します。</li>
<li>交渉がまとまったら、実際に実行します。</li>
<li>実行されたら、「幸」ポイントを支払います。</li>
</ol>

app/views/home/help.html.erb
<% provide :title, t("Need help?") %>
<%= render "devise/shared/links" %>

app/views/home/index.html.erb
<% unless user_signed_in? %>
  <%= render "home/index_not_signed_in" %>
<% else %>
  <%= render "home/index_signed_in" %>
<% end %>
<br>

<%= render "home/info" %>

app/views/home/need_help.html.erb
<% provide :title, t("Need help?") %>
<h1><%= t(yield(:title)) %></h1>
<%= render "devise/shared/links" %>

app/views/home/search.html.erb
<%= t('Search') %>
<ul data-role="listview" data-inset="true">
  <li><%= link_to t("Search ", model: User.model_name.human.pluralize(:locale)), users_path %></li>
  <li><%= link_to t("Search ", model: Offering.model_name.human.pluralize(:locale)), offerings_path %></li>
  <li><%= link_to t("Search ", model: Want.model_name.human.pluralize(:locale)), wants_path %></li>
</ul>