config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'home#index'

  match '/need_help',   to: 'home#need_help',   via: 'get'
  match '/about',       to: 'home#about',       via: 'get'
  match '/contact',     to: 'home#contact',     via: 'get'
  match '/status',      to: 'home#status',      via: 'get'
  match '/watch_list',  to: 'home#watch_list',  via: 'get'
  match '/new_display', to: 'home#new_display', via: 'get'
  match '/detailed',    to: 'home#detailed',    via: 'get'
  match '/search',      to: 'home#search',      via: 'get'

  devise_for :users, controllers: { registrations: 'user/registrations' }

  resources :users do
    member do
      get 'talks'
      get 'negotiations'
      get 'offerings'
      get 'wants'
      get 'payments'
      get 'entries'
      get 'contracts'
      get 'entrusts'
      get 'recent_contracts'
      get 'recent_entrusts'
      get :following, :followers
    end
  end
  match '/users/profile/edit', to: 'users#edit', via: 'get'

  resources :offerings
  resources :wants
  resources :entries
  resources :contracts
  resources :entrusts
  resources :messages
  resources :talks
  resources :negotiations
  resource :account
  resources :payments
  resources :entries, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  before_validation :set_subject
  belongs_to :sender_account, class_name: 'Account', foreign_key: 'sender_account_id'
  belongs_to :recepient_account, class_name: 'Account', foreign_key: 'recepient_account_id'
  has_one :entry

  scope :with, lambda { |user_account|
    where('sender_account_id = :user_account_id OR recepient_account_id = :user_account_id', user_account_id: user_account.id)
    .order('created_at DESC')
  }

  # 必須属性の検証
  validates :sender_account_id,    presence: true
  validates :recepient_account_id, presence: true
  validates :subject, presence: true

  # 金額は、0以上の整数
  validates :amount,                   presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :sender_balance_before,    presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :sender_balance_after,     presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :recepient_balance_before, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :recepient_balance_after,  presence: true, numericality: { only_integer: true, greater_than: 0 }

  validate :sender_account_id_not_equal_recepient_account_id
  validate :sender_balance_after_validity
  validate :recepient_balance_after_validity

  def partner_of(account)
    if sender_account == account
      recepient_account
    elsif recepient_account == account
      sender_account
    end
  end

  def type_for(account)
    if sender_account == account
      'withdraw'
    elsif recepient_account == account
      'deposit'
    end
  end

  def balance_before_for(account)
    if sender_account == account
      sender_balance_before
    elsif recepient_account == account
      recepient_balance_before
    end
  end

  def balance_after_for(account)
    if sender_account == account
      sender_balance_after
    elsif recepient_account == account
      recepient_balance_after
    end
  end

  def amount_for(account)
    if sender_account == account
      -amount
    elsif recepient_account == account
      amount
    end
  end

  private

  def set_subject
    self.subject = '無題' unless subject.present?
  end

  def sender_account_id_not_equal_recepient_account_id
    errors.add(:recepient_account_id, :invalid) if sender_account_id == recepient_account_id
  end

  def sender_balance_after_validity
    if amount.is_a?(Integer)
      unless sender_balance_after == (sender_balance_before - amount)
        errors.add(:sender_balance_after, :invalid)
      end
    end
  end

  def recepient_balance_after_validity
    if amount.is_a?(Integer)
      unless recepient_balance_after == (recepient_balance_before + amount)
        errors.add(:recepient_balance_after, :invalid)
      end
    end
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show]
  before_action :authenticate_user!

  def index
    @payments = Payment.with(current_user.account)
  end

  def show
  end

  def new
    @payment = Payment.new
    @recepients = User.where.not(id: current_user.id).active

    if params[:contract]
      contract = Contract.find(params[:contract])
      contract.paid_at = Time.now
      contract.save
      @payment.subject = "「#{contract.task.title}」の支払い"
      @recepients = User.where(id: contract.task.user_id)
    end

    if params[:entrust]
      entrust = Entrust.find(params[:entrust])
      entrust.paid_at = Time.now
      entrust.save
      @payment.subject = "「#{entrust.task.title}」の支払い"
      @recepients = User.where(id: entrust.user_id)
    end

=begin
    @partner_account_ids = []
    @partners.each do |partner|
      #partner.account_id = partner.account.id
      @partner_account_ids.push(partner.account.id)
    end
    #@tos = Account.where(id: partner_accounts)
=end
  end

=begin
  def edit
  end
=end

  def create
    @payment = Payment.new(payment_params)
    begin
      Account.transfer(
        sender_account: current_user.account,
        recepient_account: Account.find(@payment.recepient_account_id),
        amount: @payment.amount,
        subject: @payment.subject,
        comment: @payment.comment
      )
      redirect_to account_url, notice: t('activerecord.successful.messages.created', model: Payment.model_name.human)
    rescue
      @recepients = User.where.not(id: current_user.id).active
      render action: 'new'
    end
  end

=begin
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: t('activerecord.successful.messages.updated', :model => Payment.model_name.human) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end
=end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def payment_params
    params.require(:payment).permit(:recepient_account_id, :subject, :amount, :comment)
  end
end

app/views/payments/_form.html.erb
<%= form_for(@payment, html: { data: { ajax: false}} ) do |f| %>
  <ul data-role="listview" data-inset="true">
  <% if @payment.errors.any? %>
    <li>
      <div id="error_explanation">
        <h2><%=t "activerecord.errors.template.header.other", :model => Payment.model_name.human, :count => @payment.errors.count %></h2>

        <ul>
        <% @payment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </li>
  <% end %>

    <li class="field ui-field-contain">
      <%= label :payment, :recepient_account %>
      <%= collection_select :payment, :recepient_account_id, @recepients, :account_id, :name %>
    </li>

    <li class="field ui-field-contain">
      <%= f.label :subject %>
      <%= f.text_field :subject %>
    </li>

    <li class="field ui-field-contain">
      <%= f.label :amount %>
      <%= f.number_field :amount %>
    </li>

    <li class="field ui-field-contain">
      <%= f.label :comment %>
      <%= f.text_area :comment %>
    </li>

    <li class="actions">
<!--
      <%= f.hidden_field :direction, value: 'deposit' %>
-->
      <%= f.submit t("Submit new payment") %>
    </li>
  </ul>
<% end %>

app/views/payments/edit.html.erb
<% provide :title, t('Editing ', model: Payment.model_name.human) %>
<h1><%= yield(:title) %></h1>

<%= render 'form' %>

<%= link_to t('Show'), @payment %> |
<%= link_to t('Back'), payments_path %>

app/views/payments/index.html.erb
<% provide :locale, I18n.locale.inspect %>
<% provide :title,  t("Listing ", model: Payment.model_name.human.pluralize(:locale)) %>
<h1><%= yield(:title) %></h1>

<%= link_to t('New ', model: Payment.model_name.human), new_payment_path, class: "ui-btn" %>

<% if @payments.present? %>
  <table>
    <tr>
      <th><%= t("Person") %></th>
      <th><%= t("Amount") %></th>
      <th><%= t("Subject") %></th>
    </tr>
    <% @payments.each do |payment| %>
    <tr>
      <td><%= payment.with.name %></td>
      <td style="text-align: right;"><%= payment.payment %></td>
      <td><%= link_to payment.subject, payment %></td>
    </tr>
    <% end %>
  </table>
<% else %>
  <%= t("No transfer record.") %>
<% end %>

app/views/payments/new.html.erb
<% provide :title, t('New ', model: Payment.model_name.human) %>
<h1><%= yield(:title) %></h1>

<p><strong><%= t('Current balance') %></strong>: <%= current_user.account.balance %> <%= t('points') %></p>
<%= render 'form' %>

<%= link_to t('Back'), account_path, class: "ui-btn ui-icon-arrow-l ui-btn-icon-left" %>

<!--
<%= link_to t('Back'), payments_path, class: "ui-btn ui-icon-arrow-l ui-btn-icon-left" %>
-->

app/views/payments/show.html.erb
<% provide :title, Payment.model_name.human %>
<h1><%= yield(:title) %></h1>


<ul data-role="listview" data-inset="true">
<li>
  <strong>日時:</strong>
  <%= l(@payment.created_at) %>
</li>

<li>
  <strong>支払人:</strong>
  <%= @payment.sender_account.user.name %>
</li>

<li>
  <strong>受取人:</strong>
  <%= @payment.recepient_account.user.name %>
</li>

<li>
  <strong><%= Payment.human_attribute_name(:subject) %>:</strong>
  <%= @payment.subject %>
</li>

<li>
  <strong><%= Payment.human_attribute_name(:amount) %>:</strong>
  <%= @payment.amount %>
</li>

<li>
  <strong><%= Payment.human_attribute_name(:sender_balance_before) %>:</strong>
  <%= @payment.sender_balance_before %>
</li>

<li>
  <strong><%= Payment.human_attribute_name(:sender_balance_after) %>:</strong>
  <%= @payment.sender_balance_after %>
</li>

<li>
  <strong><%= Payment.human_attribute_name(:recepient_balance_before) %>:</strong>
  <%= @payment.recepient_balance_before %>
</li>

<li>
  <strong><%= Payment.human_attribute_name(:recepient_balance_after) %>:</strong>
  <%= @payment.recepient_balance_after %>
</li>

<li>
  <h2><%= Payment.human_attribute_name(:comment) %>:</h2>
  <p><%= simple_format @payment.comment %></p>
</li>
</ul>

  <%= link_to t('Back'), account_path, class: "ui-btn" %>
<!--
<%= link_to t('Edit'), edit_payment_path(@payment) %> |
<%= link_to t('Back'), payments_path %>
-->